sonar.projectKey=fayrus_syncret
sonar.organization=fayrus

sonar.sources=.
sonar.exclusions=docs/**
sonar.coverage.exclusions=cmd/syncret/main.go

sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out
